server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.4.101.111:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: Aa123456
    driver-class-name: com.mysql.cj.jdbc.Driver